### ISSUE TITLE
TODO: 1.0.0

### ISSUE THREAD

**Issue by Sandertv** [BlockHorizons/KillCounter#3]
TODO list for KillCounter version 1.0.0:

**Code base:**
- [ ] Add KillCounterEntity class, mirror it with a normal entity.
- [ ] Move killing spree, multi-kill and more to that entity class.
- [ ] Clean up other mess throughout the plugin.

**Providers:**
- [x] Add **at least** a MySQL provider.

**Other Additions/Changes:**
- [ ] Make money leeching only happen if the victim has enough money.
- [x] Add KDA output in /stats.
- [ ] Make a proper assist points calculation.

**Bug fixes:**
- [ ] Fix achievements never being rewarded correctly.

**Comment by SuperAlecs** [comment]
In the future can you add killstreaks?

**Comment by Sandertv** [comment]
They already exist. They're called Killing Sprees in this plugin.
